#!/bin/sh
# Copyright 2010-2013 Free Geek Vancouver
# Copyright 2010 Aaron Black
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

cannotget() {
  echo "[Error $1] Unable to download stage2. See build instructor."
  exit $1
}

cannotgetuser() {
  echo "[Error $1] Unable to download stage2."
  echo "Ensure you have entered a correct username of an account having a QC script."
  echo "(The file called 'fgqc' must be placed in the '~/public_html' directory)"
  echo "If you want the normal QC, please type 'fgqc' with nothing after it."
  exit $1
}

stage2=/tmp/fgqc.stage2

if ! ping -c 1 shop.freegeekvancouver.org >/dev/null
then
    echo "Check your network connection!"
    exit 1
fi

rm -f $stage2
if [ -n "$1" ]
then
  wget -O $stage2 --quiet http://u.shop.lan/~$1/fgqc || cannotgetuser $?
else
  wget -O $stage2 --quiet http://preseed.shop.lan/scripts/fgqc.stage2 || cannotget $?
fi
clear
sudo /bin/bash $stage2 $2

