#!/bin/sh

stage2=/tmp/fgqc.stage2

if ! ping -c 1 shop.freegeekvancouver.org
then
    echo Check your network connection!
    exit 1
fi

rm -f $stage2
wget -O $stage2 http://preseed.shop.lan/scripts/fgqc.stage2 || exit 1
clear
sudo /bin/bash $stage2
