#!/bin/sh
# Copyright 2010-2013 Free Geek Vancouver
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

in-target rm /etc/apt/apt.conf
wget -O /target/usr/local/bin/fgqc http://preseed.shop.lan/scripts/fgqc
in-target chmod +x /usr/local/bin/fgqc
apt-install $(in-target check-language-support)
in-target rm /var/lib/update-notifier/user.d/incomplete-language-support-gnome.note
echo "blacklist b43" > /target/etc/modprobe.d/blacklist-b43.conf
in-target /bin/sed -i s/enabled=1/enabled=0/ /etc/default/apport
wget -O /target/tmp/libdvdcss2.deb \
    http://files.shop.lan/install_files/libdvdcss2_$(chroot /target uname -i).deb && \
  in-target dpkg -i /tmp/libdvdcss2.deb
