#!/bin/sh

in-target rm /etc/apt/apt.conf
in-target wget -nv -O /usr/local/bin/fgqc http://preseed.shop.lan/scripts/fgqc
in-target chmod +x /usr/local/bin/fgqc
apt-install $(in-target check-language-support)
in-target rm /var/lib/update-notifier/user.d/incomplete-language-support-gnome.note
echo "blacklist b43" > /target/etc/modprobe.d/blacklist-b43.conf
in-target /bin/sed -i s/enabled=1/enabled=0/ /etc/default/apport
